# Generated by Django 3.2.9 on 2021-12-23 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Question',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('question_text', models.CharField(max_length=200)),
        #         ('question_text2', models.CharField(max_length=200)),
        #         ('pub_date', models.DateTimeField(verbose_name='date published')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Choice',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('choice_text', models.CharField(max_length=200)),
        #         ('votes', models.IntegerField(default=0)),
        #         ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_roster.question')),
        #     ],
        # ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('userId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('tell', models.CharField(max_length=20)),
                ('sex',models.CharField(max_length=1)),
                ('contract', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('deleteFlag', models.BooleanField(default=False)),
                ('updateTime', models.DateField(null=False)),
                ('addTime', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='attendances',
            fields=[
                ('attendanceId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.BigIntegerField()),
                ('yearMonth', models.CharField(max_length=6)),
                ('day', models.CharField(max_length=2)),
                ('startTime', models.DateField()),
                ('dndDateTime', models.DateTimeField()),
                ('restStartTime', models.DateTimeField()),
                ('restEndTime', models.DateTimeField()),
                ('deleteFlag', models.BooleanField(default=False)),
                ('updateTime', models.DateField(null=False)),
                ('addTime', models.BooleanField(null=True)),
            ],
        ),
    ]


