# Generated by Django 3.2.9 on 2021-12-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text2',
        ),
    ]
