# Generated by Django 3.2.9 on 2021-12-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0002_remove_question_question_text2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
