# Generated by Django 3.2.9 on 2022-01-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0002_auto_20211229_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='itotest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
