# Generated by Django 3.2.9 on 2022-01-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0003_itotest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='itotest',
            new_name='Logs',
        ),
    ]
