# Generated by Django 3.2.9 on 2021-12-29 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendances',
            name='addTime',
        ),
        migrations.RemoveField(
            model_name='attendances',
            name='attendanceId',
        ),
        migrations.RemoveField(
            model_name='attendances',
            name='day',
        ),
        migrations.RemoveField(
            model_name='attendances',
            name='deleteFlag',
        ),
        migrations.RemoveField(
            model_name='attendances',
            name='dndDateTime',
        ),
        migrations.RemoveField(
            model_name='attendances',
            name='restEndTime',
        ),
        migrations.RemoveField(
            model_name='attendances',
            name='restStartTime',
        ),
        migrations.RemoveField(
            model_name='attendances',
            name='startTime',
        ),
        migrations.RemoveField(
            model_name='attendances',
            name='updateTime',
        ),
        migrations.RemoveField(
            model_name='attendances',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='attendances',
            name='yearMonth',
        ),
        migrations.RemoveField(
            model_name='users',
            name='addTime',
        ),
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='users',
            name='deleteFlag',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tell',
        ),
        migrations.RemoveField(
            model_name='users',
            name='updateTime',
        ),
        migrations.RemoveField(
            model_name='users',
            name='userId',
        ),
    ]
