# Generated by Django 3.2.5 on 2021-11-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendanceId', models.IntegerField(verbose_name='attendanceid')),
                ('userId', models.IntegerField(verbose_name='userId')),
                ('yearMonth', models.IntegerField()),
                ('day', models.IntegerField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('restStartTime', models.DateTimeField()),
                ('restEndTime', models.DateTimeField()),
                ('updateTime', models.DateTimeField()),
                ('addTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(null=True, verbose_name='userId')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('tell', models.IntegerField(null=True, verbose_name='tell')),
                ('sex', models.CharField(max_length=1)),
                ('contract', models.IntegerField(verbose_name='contrach')),
                ('deleteFlag', models.IntegerField(verbose_name='deleteFlag')),
                ('updateTime', models.DateTimeField()),
                ('addTime', models.DateTimeField()),
            ],
        ),
    ]
