# Generated by Django 3.2.9 on 2022-02-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0004_rename_itotest_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='umaCardUniqueBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
