# Generated by Django 3.2.9 on 2022-02-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0005_umacarduniquebonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='umaSkillMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
