# Generated by Django 3.2.9 on 2022-04-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0008_skilldetailmaster_skillevaluationmaster_umamaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='umaRaceBonuMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
