# Generated by Django 3.2.9 on 2022-04-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0009_umaracebonumaster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='umaRaceBonuMaster',
            new_name='RaceBonuMaster',
        ),
    ]
