# Generated by Django 3.2.9 on 2022-04-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0010_rename_umaracebonumaster_racebonumaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='umaMessegeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
