# Generated by Django 3.2.5 on 2021-11-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0011_auto_20211124_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendanceId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='userId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleteFlag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ユーザーID'),
        ),
    ]
