# Generated by Django 3.2.5 on 2021-11-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0002_attendance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendanceId',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='attendanceid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='userId'),
        ),
    ]
