# Generated by Django 3.2.5 on 2021-11-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0003_auto_20211122_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tell',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
