# Generated by Django 3.2.5 on 2021-11-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0004_alter_user_tell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contract',
            field=models.CharField(max_length=100),
        ),
    ]
