# Generated by Django 3.2.5 on 2021-11-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0007_alter_attendance_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='startTime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
