# Generated by Django 3.2.5 on 2021-11-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0008_alter_attendance_starttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='endTime',
            new_name='endDateTime',
        ),
    ]
