# Generated by Django 3.2.5 on 2021-11-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0010_auto_20211124_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='deleteFlag',
            field=models.BooleanField(default=True, verbose_name='deleteFlag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleteFlag',
            field=models.BooleanField(default=True, verbose_name='deleteFlag'),
        ),
    ]
