# Generated by Django 3.2.5 on 2021-11-24 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0012_auto_20211124_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='addTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendanceId',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='deleteFlag',
            field=models.BooleanField(default=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='endDateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='restEndTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='restStartTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='startTime',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='updateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='userId',
            field=models.IntegerField(verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='yearMonth',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='addTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contract',
            field=models.CharField(max_length=100, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleteFlag',
            field=models.BooleanField(default=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=1, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tell',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ユーザーID'),
        ),
    ]
