# Generated by Django 3.2.5 on 2021-11-24 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_roster', '0013_auto_20211124_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='addTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='追加時間'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendanceId',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='出勤ID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='対象日'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='deleteFlag',
            field=models.BooleanField(default=True, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='endDateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='勤務終了時間'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='restEndTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='休憩終了時間'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='restStartTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='休憩開始時間'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='startTime',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='勤務開始時間'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='updateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='yearMonth',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='対象年月'),
        ),
        migrations.AlterField(
            model_name='user',
            name='addTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='追加日時'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contract',
            field=models.CharField(max_length=100, verbose_name='社員パートなど'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleteFlag',
            field=models.BooleanField(default=True, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=1, verbose_name='性別(m:男性,f:女性)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tell',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時'),
        ),
    ]
